import { ApiTableBodyDataProps, ApiTableBodyTypeColor } from "@/components/docs/layout/api-reference-table/api-table";

export const cpuArchitectureApiRefData = [
  {
    prop: "className",
    tip: "The class name of the component",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
  },
  {
    prop: "width",
    tip: "The width of the SVG",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "100%",
  },
  {
    prop: "height",
    tip: "The height of the SVG",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "100%",
  },
  {
    prop: "text",
    tip: "The text to display in the architecture diagram",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "CPU",
  },
  {
    prop: "showCpuConnections",
    tip: "Whether to show the CPU connection lines",
    type: "boolean",
    typeColor: ApiTableBodyTypeColor.Boolean,
    required: false,
    default: "true",
  },
  {
    prop: "lineMarkerSize",
    tip: "The size of the line markers in pixels",
    type: "number",
    typeColor: ApiTableBodyTypeColor.Number,
    required: false,
    default: "18",
  },
  {
    prop: "animateText",
    tip: "Whether to animate the text",
    type: "boolean",
    typeColor: ApiTableBodyTypeColor.Boolean,
    required: false,
    default: "true",
  },
  {
    prop: "animateLines",
    tip: "Whether to animate the connection lines",
    type: "boolean",
    typeColor: ApiTableBodyTypeColor.Boolean,
    required: false,
    default: "true",
  },
  {
    prop: "animateMarkers",
    tip: "Whether to animate the line markers",
    type: "boolean",
    typeColor: ApiTableBodyTypeColor.Boolean,
    required: false,
    default: "true",
  },
] satisfies ApiTableBodyDataProps;
