import {
  ApiTableBodyDataProps,
  ApiTableBodyTypeColor,
} from "@/components/docs/layout/api-reference-table/api-table";

export const shadcnUiApiRefData = [
  {
    prop: "className",
    tip: "The class name of the component",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
  },
  {
    prop: "circleText",
    tip: "The text to display in the circle shape",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "Registry",
  },
  {
    prop: "triangleText",
    tip: "The text to display in the triangle shape",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "AI",
  },
  {
    prop: "diamondText",
    tip: "The text to display in the diamond shape",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "Registry",
  },
  {
    prop: "animatedText",
    tip: "The text to display in the animated section",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "npx shadcn add",
  },
  {
    prop: "animatedBoxText",
    tip: "The text to display in the animated moving box",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "Sidebar",
  },
  {
    prop: "hintText",
    tip: "The hint text to display below the animated text",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "(components.json)",
  },
  {
    prop: "appName",
    tip: "The name of your application below four shapes",
    type: "string",
    typeColor: ApiTableBodyTypeColor.String,
    required: false,
    default: "Your App",
  },
] satisfies ApiTableBodyDataProps;
